backend/users/urls.py
from django.urls import path

from backend.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.utils import timezone
from django.views import defaults as default_views
# from rest_framework.authtoken.views import obtain_auth_token
from django.views.decorators.http import last_modified
from django.contrib.flatpages.views import flatpage
from django.views.i18n import JavaScriptCatalog
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

# sitemap
from django.contrib.sitemaps.views import sitemap
from django.contrib.flatpages.sitemaps import FlatPageSitemap

# django-sso-app
from django_sso_app.urls import (urlpatterns as django_sso_app__urlpatterns,
                                 api_urlpatterns as django_sso_app__api_urlpatterns,
                                 i18n_urlpatterns as django_sso_app_i18n_urlpatterns)
from django_sso_app.core.mixins import WebpackBuiltTemplateViewMixin

from backend.views import set_language_from_url
from backend.api.views import StatsView

from apps.uploads.urls import (urlpatterns as uploads__urlpatterns)
from apps.uploads.urls import download_link_urlpattern

last_modified_date = timezone.now()
js_info_dict = {}

urlpatterns = []
api_urlpatterns = []
_I18N_URLPATTERNS = []

urlpatterns += django_sso_app__urlpatterns
api_urlpatterns += django_sso_app__api_urlpatterns
_I18N_URLPATTERNS += django_sso_app_i18n_urlpatterns

urlpatterns += [
    # pai
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', last_modified(lambda req, **kw: last_modified_date)(JavaScriptCatalog.as_view()), js_info_dict,
        name='javascript-catalog'),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),

    # set language url
    url(r'^set_language/(?P<user_language>\w+)/$', set_language_from_url, name="set_language_from_url"),

    # flatpages sitemap
    path('sitemap.xml', sitemap, {'sitemaps': {'flatpages': FlatPageSitemap()}},
         name='django.contrib.sitemaps.views.sitemap'),
]

_I18N_URLPATTERNS += [
    path('', WebpackBuiltTemplateViewMixin.as_view(template_name='pages/home.html'), name='home'),

    # flatpages
    path('about/', flatpage, {'url': '/about/'}, name='about'),
    path('privacy-policy/', flatpage, {'url': '/privacy-policy/'}, name='privacy-policy'),
    path('legal-notes/', flatpage, {'url': '/legal-notes/'}, name='legal-notes'),
    path('media-policy/', flatpage, {'url': '/media-policy/'}, name='media-policy'),
]

if settings.I18N_PATH_ENABLED:
    urlpatterns += i18n_patterns(
        *_I18N_URLPATTERNS
    )
else:
    urlpatterns += _I18N_URLPATTERNS


# Your stuff: custom urls includes go here
urlpatterns += [
    path('users/', include('backend.users.urls', namespace='users')),

    # django-filer admin download
    url(r'^', include('filer.server.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# API URLS
""" pai
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]
"""

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            '400/',
            default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')},
        ),
        path(
            '403/',
            default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')},
        ),
        path(
            '404/',
            default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')},
        ),
        path('500/', default_views.server_error),
    ]

    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]


api_urlpatterns += [
    url(r'^api/v1/_stats/$', StatsView.as_view(), name='stats'),

    # your api here
    url(r'^api/v1/', include(uploads__urlpatterns)),
    download_link_urlpattern,
]

# extra
from .extra_urls import api_urlpatterns as extra_api_urlpatterns
if len(extra_api_urlpatterns):
    api_urlpatterns += extra_api_urlpatterns

urlpatterns += api_urlpatterns

urlpatterns += [
    path(
        "api/v1/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
    path("api/v1/schema/", SpectacularAPIView.as_view(), name="api-schema"),
]

# extra

from .extra_urls import urlpatterns as extra_urlpatterns
from .extra_urls import i18n_urlpatterns as extra_i18n_urlpatterns

if len(extra_urlpatterns) > 0:
    urlpatterns += extra_urlpatterns

if settings.I18N_PATH_ENABLED:
    if len(extra_i18n_urlpatterns) > 0:
        urlpatterns += i18n_patterns(extra_i18n_urlpatterns)
else:
    if len(extra_i18n_urlpatterns) > 0:
        urlpatterns += extra_i18n_urlpatterns

# flatpages
urlpatterns += [
    path('<path:url>', include('django.contrib.flatpages.urls')),
]

#print('URLPATTERNS', urlpatterns)

urlpatterns += [
    path(r'_health/', include('health_check.urls')),
]

backend/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, PositiveIntegerField, BooleanField
from django.conf import settings
# from django.urls import reverse
# from django.utils.translation import ugettext_lazy as _

from django_sso_app.core.apps.users.models import DjangoSsoAppUserModelMixin

from apps.ftp.utils import create_random_password


class User(AbstractUser, DjangoSsoAppUserModelMixin):
    ftp_enabled = BooleanField(default=True)
    ftp_password = CharField(max_length=100, default=create_random_password)
    ftp_quota = PositiveIntegerField(default=settings.DJANGO_UPLOADS_FTP_QUOTA_MB)

    def __init__(self, *args, **kwargs):
        super(User, self).__init__(*args, **kwargs)
        setattr(self, '__old_ftp_password', getattr(self, 'ftp_password', None))
        setattr(self, '__old_ftp_quota', getattr(self, 'ftp_quota', None))

    @property
    def ftp_password_has_changed(self):
        old_ftp_password = getattr(self, '__old_ftp_password')
        return old_ftp_password != self.ftp_password

    @property
    def ftp_quota_has_changed(self):
        old_ftp_quota = getattr(self, '__old_ftp_quota')
        return old_ftp_quota != self.ftp_quota

    #def get_relative_url(self):
    #    return reverse("users:detail", kwargs={"username": self.username})

    def create_filer_folders(self):
        from filer.models.foldermodels import Folder
        from apps.uploads.models import UploadType

        users_folder, _created = Folder.objects.get_or_create(name='users')
        user_folder, _created = Folder.objects.get_or_create(name=self.sso_id, parent=users_folder, owner=self)

        for ut in UploadType.objects.all():
            _ut_folder, _created = Folder.objects.get_or_create(name=ut.slug, parent=user_folder, owner=self)

backend/users/forms.py
from django_sso_app.core.apps.users.forms import (UserCreationForm as DjangoSsoAppUserCreationForm,
                                                  UserChangeForm as DjangoSsoAppUserChangeForm)


class UserChangeForm(DjangoSsoAppUserChangeForm):
    pass


class UserCreationForm(DjangoSsoAppUserCreationForm):
    pass

backend/api/views.py
import logging

import socket

from django.conf import settings

from django.contrib.sites.models import Site

from rest_framework import status
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView

from django_sso_app.core.apps.users.serializers import UserSerializer

from apps.permissions import is_staff
from apps.utils import local_space_available
from apps.settings import CURRENT_DIR, USERS_FOLDER, MAX_FILE_SIZE_MB, MINIMUM_FREE_SPACE_MB
from apps.uploads.models import UploadType
from apps.uploads.serializers import UploadTypeSerializer

from backend import dist_name, __version__

logger = logging.getLogger('backend.api')


class StatsView(APIView):
    """
    Return instance stats.
    """

    permission_classes = (AllowAny,)

    def get(self, request, format=None):
        try:
            health_status = 'red'
            free_space_mb = int(local_space_available(CURRENT_DIR) / (1024 * 1024))

            context = {
                'request': request
            }

            logger.info(
                'Free space (MB) in folder {}: {}. Minimum free space: {}'.format(USERS_FOLDER,
                                                                                  free_space_mb,
                                                                                  MINIMUM_FREE_SPACE_MB))

            if free_space_mb > MINIMUM_FREE_SPACE_MB:
                health_status = 'green'
            else:
                health_status = 'yellow'

            sites = []
            for s in Site.objects.all().order_by('id'):
                sites.append(
                    {
                        'url': settings.ACCOUNT_DEFAULT_HTTP_PROTOCOL + '://'
                               + s.domain
                    })

            upload_types = UploadType.get_user_upload_types(request.user)

            upload_types_serializer = UploadTypeSerializer(upload_types,
                                                           context={
                                                               'request': request},
                                                           many=True)

            data = {
                'app_name': dist_name,
                'deployment_environment': settings.DEPLOYMENT_ENV,
                'revision': settings.REPOSITORY_REV,
                'version': __version__,

                'user': UserSerializer(request.user, context=context).data if request.user.is_authenticated else None,

                'status': health_status,
                'instances': sites,
                'upload_types': upload_types_serializer.data,
                'max_file_size_mb': MAX_FILE_SIZE_MB,

                'host': socket.gethostname()
            }

            if is_staff(request.user):
                data['free_space_mb'] = free_space_mb
                data['meta'] = str(request.META.items())

            return Response(data, status.HTTP_200_OK)

        except Exception as e:
            logger.exception('Error getting stats')
            print('StatsView Exception', e)
            return Response('Error getting stats', status.HTTP_500_INTERNAL_SERVER_ERROR)

backend/pages/views.py
from django.conf import settings

from meta.views import MetadataMixin

from ...core.mixins import WebpackBuiltTemplateViewMixin
from ... import app_settings


class HomeView(MetadataMixin, WebpackBuiltTemplateViewMixin):
    description = settings.META_DESCRIPTION
    url = app_settings.APP_URL

backend/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

backend/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse

from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["first_name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

backend/views.py
import logging

from urllib.parse import urlsplit

from django.utils import translation
from django.shortcuts import redirect
from django.conf import settings

logger = logging.getLogger('backend')


def set_language_from_url(request, user_language):
    prev_lang = request.session.get(translation.LANGUAGE_SESSION_KEY, request.LANGUAGE_CODE)

    translation.activate(user_language)
    request.session[translation.LANGUAGE_SESSION_KEY] = user_language

    url = request.META.get('HTTP_REFERER', '/')
    parsed = urlsplit(url)

    _url = parsed.path
    if len(_url) > 1:
        if settings.I18N_PATH_ENABLED:
            _url = '/{}/'.format(user_language) + _url.lstrip('/{}/'.format(prev_lang))
    else:
        _url = '/'

    return redirect(_url)

backend/templates/partials/checkbox_field.html
<div class="form-check form-check-inline {{ field_extra_classes }}">
  <input class="form-check-input" type="checkbox"
     id="id_{{ field.name }}"
     name="{{ field.name }}"
     {% if field_value %} value="{{ field_value }}" {% endif %}>
  <label class="form-check-label"  for="id_{{ field.name }}" {% if field.field.required %} class="requiredField" {% endif %}>
    {{ field.label }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
  </label>
  {% for form_field, errors in form.errors.items %}
    {% if form_field == field.name %}{% for error in errors %}<small class="text-danger">{{ error|escape }}</small>{% endfor %}{% endif %}
  {% endfor %}
</div>

backend/templates/partials/country_selector_field.html
{% load countries %}

<div class="form-group col {{ field_extra_classes }}">
  <div class="bootstrap-select-wrapper">
  <select name="{{ field.name }}" id="id_{{ field.name }}" data-live-search="true" {% if field.country.required %} required {% endif %}>
  <option {% if field_value %} value="{{ field_value }}" {% else %}  value="{{ field.value|default_if_none:'' }}" {% endif %}>{{ field.value.name }}</option>
  {% get_countries as countries %}
  {% for country in countries %}
    {% if country.code != form.country.value.code %}
      <option name="country" value="{{ country.code }}">{{ country.name }}</option>
    {% endif %}
  {% endfor %}
  </select>
  </div>
  {% for form_field, errors in form.errors.items %}
    {% if form_field == field.name %}{% for error in errors %}<small class="text-danger">{{ error|escape }}</small>{% endfor %}{% endif %}
  {% endfor %}
</div>

backend/templates/partials/date_field.html
<div class="form-group col {{ field_extra_classes }}">
  <input type="date" class="form-control" id="id_{{ field.name }}" name="{{ field.name }}"
         {% if field_value %} value="{{ field_value }}" {% else %}  value="{{ field.value|default_if_none:'' }}" {% endif %}
         {% if field.field.required %} required {% endif %} >
  <label for="id_{{ field.name }}"  class="active {% if field.field.required %} requiredField {% endif %}">
    {{ field.label }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
  </label>
  {% for form_field, errors in form.errors.items %}
    {% if form_field == field.name %}{% for error in errors %}<small class="text-danger">{{ error|escape }}</small>{% endfor %}{% endif %}
  {% endfor %}
</div>

backend/templates/partials/file_field.html
<div class="form-group col {{ field_extra_classes }}">
  <input type="file" class="form-control" id="id_{{ field.name }}" name="{{ field.name }}"
         {% if field.field.required %} required {% endif %} >
  <label for="id_{{ field.name }}" {% if field.field.required %} class="requiredField active" {% endif %}>
    {{ field.label }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
  </label>
  {% for form_field, errors in form.errors.items %}
    {% if form_field == field.name %}{% for error in errors %}<small class="text-danger">{{ error|escape }}</small>{% endfor %}{% endif %}
  {% endfor %}
</div>

backend/templates/partials/google_analytics_site_tag.html
{% if GOOGLE_ANALYTICS_TRACKING_ID and GOOGLE_ANALYTICS_TRACKING_ID.strip %}
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ GOOGLE_ANALYTICS_TRACKING_ID }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{ GOOGLE_ANALYTICS_TRACKING_ID }}');
</script>
{% endif %}

backend/templates/partials/header-full.html
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}

{% url 'home' as home_url %}

<header class="it-header-wrapper">
  <div class="it-header-slim-wrapper">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="it-header-slim-wrapper-content">
            <a class="d-none d-lg-block navbar-brand" href="/">{{ APP_DOMAIN }}</a>
            <div class="nav-mobile">
              <nav>

              </nav>
            </div>

            <div class="it-header-slim-right-zone">
              <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false">
                  <span>{{ LANGUAGE_CODE|upper }}</span>
                  <svg class="icon d-none d-lg-block">
                    <use xlink:href="/static/bootstrap-italia/svg/sprite.svg#it-expand"></use>
                  </svg>
                </a>
                <div class="dropdown-menu" style="">
                  <div class="row">
                    <div class="col-12">
                      <div class="link-list-wrapper">
                        <ul class="link-list">
                          {% for lang in LANGUAGES %}
                          <li>
                            <a class="list-item" href="{% url 'set_language_from_url' lang.0 %}"><span>{{ lang.1|upper }}</span></a>
                          </li>
                          {% endfor %}
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <a class="btn btn-primary btn-icon btn-full"
                 {% if request.user.is_authenticated %}
                    href="{% url 'users:detail' request.user.username %}" title="User" aria-label="User"
                 {% else %}
                    href="{% url 'account_login' %}" title="{% trans 'Sign In' %}" aria-label="{% trans 'Sign In' %}"
                 {% endif %}
                >
                <span class="rounded-icon">
                  <svg class="icon icon-primary">
                    <use xlink:href="/static/bootstrap-italia/svg/sprite.svg#it-user"></use>
                  </svg>
                </span>
                {% if request.user.is_authenticated %}
                <span class="d-none d-lg-block">{{ request.user }}</span>
                {% else %}
                <span class="d-none d-lg-block">{% trans 'Sign In' %}</span>
                {% endif %}
              </a>
            </div>


          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="it-nav-wrapper">
    <div class="it-header-center-wrapper">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="it-header-center-content-wrapper">
              <div class="it-brand-wrapper">
                <a href="/">
                  <svg class="icon">
                    <use xlink:href="/static/bootstrap-italia/svg/sprite.svg#it-code-circle"></use>
                  </svg>
                  <div class="it-brand-text">
                    <h2 class="no_toc">{{ APP_DOMAIN }}</h2>
                    <h3 class="no_toc d-none d-md-block">{{ META_DESCRIPTION }}</h3>
                  </div>
                </a>
              </div>
              <div class="it-right-zone">
                <div class="it-socials d-none d-md-flex">
                  {% comment %}
                  <ul>
                    <li>
                      <a href="#" aria-label="Github" target="_blank">
                        <svg class="icon">
                          <use xlink:href="/static/bootstrap-italia/svg/sprite.svg#it-github"></use>
                        </svg>
                      </a>
                    </li>
                  </ul>
                  {% endcomment %}
                </div>
                <div class="it-search-wrapper">
                  <span class="d-none d-md-block">Cerca</span>
                  <a class="search-link rounded-icon" aria-label="Cerca" href="#">
                    <svg class="icon">
                      <use xlink:href="/static/bootstrap-italia/svg/sprite.svg#it-search"></use>
                    </svg>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="it-header-navbar-wrapper">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <!--start nav-->
            <nav class="navbar navbar-expand-lg has-megamenu">
              <button class="custom-navbar-toggler" type="button" aria-controls="nav02" aria-expanded="false" aria-label="Toggle navigation" data-target="#nav02">
                <svg class="icon">
                  <use xlink:href="/static/bootstrap-italia/svg/sprite.svg#it-burger"></use>
                </svg>
              </button>
              <div class="navbar-collapsable" id="nav02" style="display: none;">
                <div class="overlay" style="display: none;"></div>
                <div class="close-div sr-only">
                  <button class="btn close-menu" type="button"><span class="it-close"></span>close</button>
                </div>
                <div class="menu-wrapper">
                  <ul class="navbar-nav">

                    <li class="nav-item"><a class="nav-link {% if request.path == home_url %} active {% endif %}" href="{% url 'home' %}"><span>Home</span><span class="sr-only">current</span></a></li>
                    <li class="nav-item"><a class="nav-link {% if request.path == about_url %} active {% endif %}" href="{% url 'about' %}"><span>About</span></a></li>

                    {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown megamenu">
                      <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false">
                        <span>Account</span>
                        <svg class="icon icon-xs">
                          <use xlink:href="/static/bootstrap-italia/svg/sprite.svg#it-expand"></use>
                        </svg>
                      </a>
                      <div class="dropdown-menu">
                        <div class="row">
                          <div class="col-12 col-lg-3">
                            <div class="link-list-wrapper">
                              <ul class="link-list">
                                <li>
                                  <h3 class="no_toc">User</h3>
                                </li>
                                <li><a class="list-item" href="{% url 'users:detail' request.user.username  %}"><span>View User</span></a></li>
                                <li><a class="list-item" href="{% url 'users:update' %}"><span>Update User</span></a></li>
                              </ul>
                            </div>
                          </div>
                          <div class="col-12 col-lg-3">
                            <div class="link-list-wrapper">
                              <ul class="link-list">
                                <li>
                                  <h3 class="no_toc">{% trans 'Profile' %}</h3>
                                </li>
                                <li><a class="list-item" href="{% url 'profile' %}"><span>{% trans 'View Profile' %}</span></a></li>
                                <li><a class="list-item" href="{% url 'profile.update' %}"><span>{% trans 'Update Profile' %}</span></a></li>
                              </ul>
                            </div>
                          </div>
                          <div class="col-12 col-lg-3">
                            <div class="link-list-wrapper">
                              <ul class="link-list">
                                  <li>
                                    <h3 class="no_toc">{% trans 'Contacts' %}</h3>
                                  </li>
                                  <li><a class="list-item" href="{% url 'account_email' %}"><span>{% trans 'E-mail' %}</span></a></li>
                                  <li><a class="list-item" href="{% url 'account_change_password' %}"><span>{% trans 'Change password' %}</span></a></li>
                              </ul>
                            </div>
                          </div>
                          <div class="col-12 col-lg-3">
                            <div class="link-list-wrapper">
                              <ul class="link-list">
                                  <li><a class="list-item " href="{% url 'account_logout' %}"><span class="text-danger">{% trans 'Sign Out' %}</span></a></li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </li>


                    {% else %}

                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false">
                        <span>Account</span>
                        <svg class="icon icon-xs">
                          <use xlink:href="/static/bootstrap-italia/svg/sprite.svg#it-expand"></use>
                        </svg>
                      </a>
                      <div class="dropdown-menu">
                        <div class="link-list-wrapper">
                          <ul class="link-list">
                            <li><a class="list-item" href="{% url 'account_signup' %}"><span>{% trans 'Sign Up' %}</span></a></li>
                            <li><a class="list-item" href="{% url 'account_login' %}"><span>{% trans 'Sign In' %}</span></a></li>
                          </ul>
                        </div>
                      </div>
                    </li>

                    {% endif %}


                  </ul>
                </div>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

backend/templates/partials/number_field.html
<div class="form-group col {{ field_extra_classes }}">
  <input type="number" class="form-control" id="id_{{ field.name }}" name="{{ field.name }}"
         {% if field_value %} value="{{ field_value }}" {% else %}  value="{{ field.value|default_if_none:0 }}" min="0" {% endif %}
         {% if field.field.required %} required {% endif %} >
  <label for="id_{{ field.name }}" {% if field.field.required %} class="requiredField" {% endif %}>
    {{ field.label }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
  </label>
  {% for form_field, errors in form.errors.items %}
    {% if form_field == field.name %}{% for error in errors %}<small class="text-danger">{{ error|escape }}</small>{% endfor %}{% endif %}
  {% endfor %}
</div>

backend/templates/partials/password_field.html
<div class="form-group col {{ field_extra_classes }}">
  <input type="password" class="form-control" id="id_{{ field.name }}" name="{{ field.name }}" {% if field.field.required %} required {% endif %}>
  <label for="id_{{ field.name }}" {% if field.field.required %} class="requiredField" {% endif %}>
    {{ field.label }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
  </label>
  {% for form_field, errors in form.errors.items %}
    {% if form_field == field.name %}{% for error in errors %}<small class="text-danger">{{ error|escape }}</small>{% endfor %}{% endif %}
  {% endfor %}
</div>

backend/templates/partials/text_field.html
<div class="form-group col {{ field_extra_classes }}">
  <input type="text" class="form-control" id="id_{{ field.name }}" name="{{ field.name }}"
         {% if field_value %} value="{{ field_value }}" {% else %}  value="{{ field.value|default_if_none:'' }}" {% endif %}
         {% if field.field.required %} required {% endif %} >
  <label for="id_{{ field.name }}" {% if field.field.required %} class="requiredField" {% endif %}>
    {{ field.label }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
  </label>
  {% for form_field, errors in form.errors.items %}
    {% if form_field == field.name %}{% for error in errors %}<small class="text-danger">{{ error|escape }}</small>{% endfor %}{% endif %}
  {% endfor %}
</div>

backend/templates/partials/textarea_field.html
<div class="form-group col {{ field_extra_classes }}">
  <textarea class="form-control" id="id_{{ field.name }}" name="{{ field.name }}" {% if field.required %} required {% endif %}>{{ field.value|default_if_none:'' }}</textarea>
  <label for="id_{{ field.name }}" {% if field.field.required %} class="requiredField" {% endif %}>
    {{ field.label }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
  </label>
  {% for form_field, errors in form.errors.items %}
    {% if form_field == field.name %}{% for error in errors %}<small class="text-danger">{{ error|escape }}</small>{% endfor %}{% endif %}
  {% endfor %}
</div>